# Generated by Django 4.2 on 2023-08-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
    ]
